### ISSUE TITLE
Training Dataset

### ISSUE THREAD

**Issue by orzanai** [mukulkhanna/FHDR#15]
Hi, thank you for your contributions to HDRI area, I really like the job you have done here. 
I want to ask if there is an available dataset for training to train model towards more iterations. I'd be happy to see the results.
Looking forward your answer!

**Comment by mukulkhanna** [comment]
Hi @testerrth, thanks for reaching out.

I, unfortunately, don't have access to the training dataset anymore.

**Comment by orzanai** [comment]
> 

Thank you for your answer!
