### ISSUE TITLE
RuntimeError: normal_ expects std > 0.0, but found std=0

### ISSUE THREAD

**Issue by seyranakdemir** [mukulkhanna/FHDR#2]
start_epoch = 1
    model.apply(weights_init)

 m.weight.data.normal_(0.0, 0.0)
I take error this code in train.py file=> RuntimeError: normal_ expects std > 0.0, but found std=0

Can you tell me, how can i get

**Comment by mukulkhanna** [comment]
You can try a very small normal value, like `1e-4`, instead of `0.0`.

```
m.weight.data.normal_(0.0, 1e-3)
```
