### ISSUE TITLE
About model output

### ISSUE THREAD

**Issue by YinengXiong** [mukulkhanna/FHDR#7]
Hello! 
According to data_loader.py, the GT(HDR) image is in range [0, +inf) and normalized the GT by -0.5 and then div 0.5, that is in range[-1, +inf)
the input(LDR) image is in range [0, 255] and also normalized by mean(0.5) and std(0.5) and that is in range[-1, 1]
Your FHDR model has one Tanh layer at the end of the model, so how do you generate output >1 ?

**Comment by sunyclj** [comment]
@YinengXiong Hi,I have my doubts about that too.so,I set the gt range between [0,1] by np.interp,and then normalized to [-1,1].but,I'm not sure that's the right approach.

**Comment by mukulkhanna** [comment]
> Your FHDR model has one Tanh layer at the end of the model, so how do you generate output >1 ?

Apologies for the extremely late reply. Yes, the network's output is between [-1,+1], but we do a linear transformation on it to bring it between [0,1] before we write the image (which we consider as the final output of our method). You can find this normalization of the network's prediction [here](https://github.com/mukulkhanna/FHDR/blob/01a21e760c1c38e82a9a49885cb4dbe5f7754045/util.py#L44).

**Comment by sunyclj** [comment]
@mukulkhanna I have a question.Hope to get your help.The pixel value of the  .hdr format image is large in the dataset ,for example,26624.0.When saved,  the value range is [0,1]. Is the image information obtained not lost ? Open the saved .hdr file,when EV=0, the screen is darker.
![image](https://user-images.githubusercontent.com/44860428/159861000-bb8c525d-c798-4db6-83a7-0c8e2623bfd8.png)
